runtime: go122

instance_class: F1

env_variables:
    INTERNAL_CACHE_EXPIRE_SECONDS: "300"
    RUNNING_ENV: "PROD"
    ALLOWED_CHARS: "abcdefghijklmnopqrstuvwxyz0123456789"
    DEFAULT_RANDOM_STRING_SIZE: 4
    DEFAULT_DURATION: 2592000 # 30 days
    REDIS_HOST: "10.142.0.2"
    REDIS_PORT: "6379"
    REDIS_PASSWORD_RESOURCE_ID: "projects/811075979077/secrets/redirectory-redis-password/versions/latest"
    API_KEY_RESOURCE_ID: "projects/811075979077/secrets/redirectory-api-key/versions/latest"

automatic_scaling:
    max_instances: 1
    min_instances: 1
