runtime: go122

instance_class: F1

env_variables:
    INTERNAL_CACHE_EXPIRE_SECONDS: "300"
    RUNNING_ENV: "PROD"
    ALLOWED_CHARS: "abcdefghijklmnopqrstuvwxyz0123456789-_"
    DEFAULT_RANDOM_STRING_SIZE: 4

automatic_scaling:
    max_instances: 1
    min_instances: 1
