runtime: go122

instance_class: F1

env_variables:
    INTERNAL_CACHE_EXPIRE_SECONDS: "300"
    RUNNING_ENV: "PROD"
    SERVER_PORT: 8080
    ALLOWED_CHARS: "abcdefghijklmnopqrstuvwxyz0123456789"
    DEFAULT_RANDOM_STRING_SIZE: 4
    DEFAULT_DURATION: 2592000 # 30 days
    REDIS_PORT: "39653"
    REDIS_DB: 0
    REDIS_HOST_RESOURCE_ID: "projects/811075979077/secrets/redirectory-redis-instance-host/versions/latest"
    REDIS_PASSWORD_RESOURCE_ID: "projects/811075979077/secrets/redirectory-redis-password/versions/latest"
    API_KEY_RESOURCE_ID: "projects/811075979077/secrets/redirectory-api-key/versions/latest"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

automatic_scaling:
    max_instances: 1
    min_instances: 1
